- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 516cc9fa72ad09699f2c03ffbd0aa7f60d75b59a
  hooks:
    - id: flake8
      args: ['--ignore=E501,E128,F403']
    - id: trailing-whitespace
    - id: debug-statements
    - id: check-added-large-files
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: end-of-file-fixer

- repo: git://github.com/Lucas-C/pre-commit-hooks
  sha: 1320d84cf315728e6ac6cca83bd80e3c732f53df
  hooks:
    - id: forbid-tabs
